### ISSUE TITLE
 WIFI CONNECTION PROBLEM - RTK FACET GN RTK RECEIVER

### ISSUE THREAD

**Issue by Raulricardo23** [sparkfun/SparkFun_RTK_Firmware_Binaries#3]
Lately I have had a problem trying to connect my Base to my cell phone.

1.- I put my Base so that everything is positioned globally well up to that point.

2.- The problem is when I put it in CONFIG mode to be able to configure it from my cell phone, it doesn't let me log in, it disconnects.
- it connects but after a short while it takes me out of the wifi and I connect it again
(the base equipment screen is in config mode) and I just can't
enter via cell phone. connects and disconnects.
- It connects sometimes and everything is fine and when I want to save the changes I see that it does not save and I bother the computer and it restarts for no apparent reason.
- other times I connect it to my cell phone and it disconnects and I say why and I turn to the computer and it restarts without me doing anything.
-as the device is connected and I get on the cell phone to enter and I do not detect a signal and the device restarts itself without being able to access the Wi-Fi

3.- Lately I have installed the firmware to see if this will remove this annoying issue, but it is getting worse and worse with each update that is made.

Does anyone know the solution to this problem.

EQUIPMENT: RTK FACET GN RTK RECEIVER
FIRWARE 5.0 INSTALLED

CELL PHONE: OPPO reno 6

**Comment by nseidle** [comment]
Closing, see cross posted issue [748](https://github.com/sparkfun/SparkFun_RTK_Firmware/issues/748).
